server:
  port: 9191

spring:
  config:
    import: "configserver:${SPRING_CONFIG_SERVER_ADDRESS:http://localhost:9292/}"
  application:
    name: licensing-service
  profiles:
    active: "${SPRING_ACTIVE_PROFILE:local}"

logging:
  level:
    root: debug