server:
  port: 9191

spring:
  config:
    import: "configserver:${SPRING_CONFIG_SERVER_ADDRESS:http://localhost:9292/}"
  application:
    name: licensing-service
  profiles:
    active: "${SPRING_ACTIVE_PROFILE:local}"

logging:
  level:
    root: info
    net.dmly: debug

resilience4j.circuitbreaker:
  instances:
    LicenseService-findAllByOrganizationId:
      register-health-indicator: true
      sliding-window-type: COUNT_BASED
      sliding-window-size: 10
      minimum-number-of-calls: 5
      permitted-number-of-calls-in-half-open-state: 3
      wait-duration-in-open-state: 10s
      failure-rate-threshold: 50
      slow-call-rate-threshold: 100
      slow-call-duration-threshold: 2s
      record-exceptions:
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException

resilience4j.bulkhead:
    instances:
      LicenseService-findAllByOrganizationId-bulkhead:
        max-wait-duration: 2ms
        max-concurrent-calls: 20

resilience4j.thread-pool-bulkhead:
  instances:
    LicenseService-findAllByOrganizationId-bulkhead:
      max-thread-pool-size: 1
      core-thread-pool-size: 1
      queue-capacity: 1

